plugins:
  - docker#v3.6.0:
      image: "node:14"
      always-pull: true

steps:
  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build
  
  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo " Launch the rocket"
    key: deploy
    depends_on: test
  
  - label: ":hammer: Example Script"
    command: "tests.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
