steps:
  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build
  
  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo " Launch the rocket"
    key: deploy
    depends_on: test
  
  - name: ":docker: Build and Push Docker Image"
    plugins:
      - docker#v3.3.0:
          image: my-image:tag
          workdir: /root/dockerfile
          environment:
            - DOCKER_BUILDKIT=1
            - BUILDKIT_PROGRESS=plain
    env:
      # Set any required environment variables
      - MY_ENV_VAR=Dev
    command:
      - docker build -t your-docker-image:tag .
      - docker push your-docker-image:tag
  
  - label: ":hammer: Example Script"
    command: "tests.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
