steps:
  - label: "Login to AWS ECR"
    plugins:
      - docker-compose#3.0.0:  # Replace with the actual plugin version
          build: "/root/dockerfile/Dockerfile"  # Specify the path to your Dockerfile
          tag: "lokesh:latest"
    key: "docker-login"

agents:
  queue: "default"
